# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmodel', '0002_auto_20170325_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='user',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
