# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmodel', '0003_auto_20170325_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('proj_type', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('budget', models.CharField(blank=True, max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='company_likes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='skill_likes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
